POST http://localhost:8000/notes/addnote
Content-Type: application/json

{
  "userId":"1",
  "noteDescription":"its Ndamulelo"
}

###

PUT http://localhost:8000/notes/modifynote/23
Content-Type: application/json

{
  "noteDescription":"Updated version no.2"
}

###
GET http://localhost:8000/notes/fetchnote/

###

DELETE http://localhost:8000/notes/deletenote/23